// <auto-generated />
using System;
using AracServis.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AracServis.Migrations
{
    [DbContext(typeof(ServisDbContext))]
    [Migration("20260220092251_TamSistemSenkronizasyon")]
    partial class TamSistemSenkronizasyon
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AracServis.Models.Arac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("marka");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("model");

                    b.Property<int>("MusteriId")
                        .HasColumnType("int")
                        .HasColumnName("musteri_id");

                    b.Property<string>("Plaka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("plaka");

                    b.Property<string>("SasiNo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sasi_no");

                    b.Property<int?>("Yil")
                        .HasColumnType("int")
                        .HasColumnName("yil");

                    b.HasKey("Id");

                    b.HasIndex("MusteriId");

                    b.ToTable("Araclar", (string)null);
                });

            modelBuilder.Entity("AracServis.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("AracServis.Models.Musteri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ad_soyad");

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("adres");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("EPosta")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("e_posta");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("telefon");

                    b.HasKey("Id");

                    b.ToTable("Musteriler", (string)null);
                });

            modelBuilder.Entity("AracServis.Models.Odeme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OdemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("OdemeTipi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OdenenTutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ServisKaydiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServisKaydiId");

                    b.ToTable("Odemeler");
                });

            modelBuilder.Entity("AracServis.Models.Parca", b =>
                {
                    b.Property<int>("ParcaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParcaID"));

                    b.Property<decimal>("BirimFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ParcaAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stok")
                        .HasColumnType("int");

                    b.HasKey("ParcaID");

                    b.ToTable("Parcalar");
                });

            modelBuilder.Entity("AracServis.Models.Personel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("durum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ise_giris_tarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("maas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("pozisyon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sifre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("soyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("personeller");
                });

            modelBuilder.Entity("AracServis.Models.Randevu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AracId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CikisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Durum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GirisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Km")
                        .HasColumnType("int");

                    b.Property<decimal?>("ToplamUcret")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AracId");

                    b.ToTable("Randevular");
                });

            modelBuilder.Entity("AracServis.Models.ServisKaydi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("IscilikTutari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ParcaTutari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.Property<int>("RandevuId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonelId");

                    b.HasIndex("RandevuId");

                    b.ToTable("ServisKayitlari");
                });

            modelBuilder.Entity("AracServis.Models.ServisParca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Adet")
                        .HasColumnType("int");

                    b.Property<int>("ParcaId")
                        .HasColumnType("int");

                    b.Property<int>("ServisKaydiId")
                        .HasColumnType("int");

                    b.Property<decimal>("ToplamFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ParcaId");

                    b.HasIndex("ServisKaydiId");

                    b.ToTable("ServisParcalari");
                });

            modelBuilder.Entity("AracServis.Models.Arac", b =>
                {
                    b.HasOne("AracServis.Models.Musteri", "Musteri")
                        .WithMany("Araclar")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("AracServis.Models.Odeme", b =>
                {
                    b.HasOne("AracServis.Models.ServisKaydi", "ServisKaydi")
                        .WithMany()
                        .HasForeignKey("ServisKaydiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServisKaydi");
                });

            modelBuilder.Entity("AracServis.Models.Randevu", b =>
                {
                    b.HasOne("AracServis.Models.Arac", "Arac")
                        .WithMany()
                        .HasForeignKey("AracId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arac");
                });

            modelBuilder.Entity("AracServis.Models.ServisKaydi", b =>
                {
                    b.HasOne("AracServis.Models.Personel", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AracServis.Models.Randevu", "Randevu")
                        .WithMany()
                        .HasForeignKey("RandevuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");

                    b.Navigation("Randevu");
                });

            modelBuilder.Entity("AracServis.Models.ServisParca", b =>
                {
                    b.HasOne("AracServis.Models.Parca", "Parca")
                        .WithMany()
                        .HasForeignKey("ParcaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AracServis.Models.ServisKaydi", "ServisKaydi")
                        .WithMany()
                        .HasForeignKey("ServisKaydiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parca");

                    b.Navigation("ServisKaydi");
                });

            modelBuilder.Entity("AracServis.Models.Musteri", b =>
                {
                    b.Navigation("Araclar");
                });
#pragma warning restore 612, 618
        }
    }
}
